### PR TITLE
[#23] Fix navigation after feature creation

### LINKED ISSUE #23: App navigates to incorrect product screen after new feature creation
### Affected version

v.1.3

### Bug description

After successfully creating a new feature within the app, the user is not redirected to the expected product screen. Instead, the app lands on a different or default screen, disrupting the expected post-creation workflow.

**Affected Area:** Navigation / Feature Creation Flow

**Steps to Reproduce:**
1. Log into the application.
2. Navigate to the feature creation screen.
3. Fill in all required fields to create a new feature.
4. Submit the creation form (tap "Save" / "Create").
5. Observe the screen that appears after the feature is created.

**Expected Result:**
The app should open the correct product screen associated with the newly created feature (e.g., the product detail page or the product list where the feature belongs).

**Actual Result:**
The app opens an incorrect screen. This could be a default, unrelated, or previous screen.

### PR DESCRIPTION
**Pull request by shruthikha**
## Description
Fixes #23

This PR fixes an issue where, after creating a new feature, the application redirects to an incorrect screen (dashboard) instead of the expected product-related feature screen.

The navigation logic has been updated to redirect users to the feature list view of the selected product after creating or updating a feature.

---

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

---

## How Has This Been Tested?
- Manually tested feature creation flow
- Verified that after creating a feature, the app navigates to the correct feature list screen instead of the dashboard

---

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/main/java/com/owino/desktop/features/FeatureFormView.java [hunk 1]
```diff
@@ -303,7 +303,9 @@ private void updateFeature() {
             successAlert.setContentText("Feature updated successfully!");
             if (successAlert.showAndWait().isPresent()){
                 successAlert.close();
-                EventBus.getDefault().post(new OSQANavigationEvents.OpenDashboardEvent());
+                EventBus.getDefault().post(
```
Comment (samuelowino) [inline src/main/java/com/owino/desktop/features/FeatureFormView.java]: Elegant fix 👍🏿
